//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VonderkWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleMap
    {
        public int MapID { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Description { get; set; }
        public string Locality { get; set; }
        public string Route { get; set; }
        public Nullable<int> StreetNumber { get; set; }
        public string AdminAreaL1 { get; set; }
        public string AdminAreaL2 { get; set; }
    }
}
