//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VonderkWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenTrabajo
    {
        public int ID { get; set; }
        public Nullable<int> Orden { get; set; }
        public string Nombre { get; set; }
        public int TrabajoId { get; set; }
    
        public virtual Trabajo Trabajo { get; set; }
    }
}
