//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VonderkWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAsset
    {
        public int AssetID { get; set; }
        public int ProductID { get; set; }
        public string AssetType { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public short SortOrder { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
