//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VonderkWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LuminariaEntities : DbContext
    {
        public LuminariaEntities()
            : base("name=LuminariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArchivoFicha> ArchivoFichas { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<ImagenProducto> ImagenProductoes { get; set; }
        public virtual DbSet<ImagenTrabajo> ImagenTrabajoes { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Slide> Slides { get; set; }
        public virtual DbSet<Trabajo> Trabajoes { get; set; }
        public virtual DbSet<ArchivoExtra> ArchivoExtras { get; set; }
    }
}
